# Independent settings for the local costmap
local_costmap:
  map_type: costmap
  resolution: 0.05

  global_frame    : odom
  robot_base_frame: base_link
  transform_tolerance: 0.2

  update_frequency : 5.0
  publish_frequency: 2.0

  static_map    : false
  rolling_window: true
  width         : 5.0
  height        : 5.0
  resolution    : 0.03

  cost_scaling_factor: 2.0

  plugins:
  - name: laser_layer
    type: 'costmap_2d::ObstacleLayer'
  - name: footprint_layer
    type: 'costmap_2d::FootprintLayer'
  - name: inflation_layer
    type: 'costmap_2d::InflationLayer'

  laser_layer:
    enabled: true
    observation_sources: base_scan

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan_filtered
      expected_update_rate: 0.3
      observation_persistence: 0.0
      marking: true
      clearing: true
      raytrace_range: 2.5
      obstacle_range: 3.0
      min_obstacle_height: -0.1
      max_obstacle_height: 0.2

  footprint_layer:
    enabled: true

  inflation_layer:
    enabled: true
    robot_radius: 0.5
    inflation_radius: 0.45
